import { Download, Film, ShieldCheck, X } from 'lucide-react'
import { artifactUrl } from '../../api/client'
import type { Artifact, RunRecord } from '../../types/run'

export function BriefingVideoDialog({ run, artifact, onClose }: {
  run: RunRecord
  artifact: Artifact
  onClose: () => void
}) {
  const source = artifactUrl(artifact.download_url)
  return <div className="drawer-backdrop briefing-backdrop" role="presentation" onMouseDown={onClose}>
    <section className="briefing-dialog" role="dialog" aria-modal="true" aria-labelledby="briefing-title" onMouseDown={(event) => event.stopPropagation()}>
      <header>
        <div><span className="eyebrow"><Film size={14} /> Veo field briefing</span><h2 id="briefing-title">A visual briefing for the selected habitat</h2></div>
        <button className="icon-button" onClick={onClose} aria-label="Close field briefing"><X size={19} /></button>
      </header>
      <video controls playsInline preload="metadata" aria-label="AI-generated habitat field briefing">
        <source src={source} type="video/mp4" />
        Your browser does not support embedded video.
      </video>
      <div className="briefing-disclaimer"><ShieldCheck size={18} /><div><strong>Illustrative communication—not scientific evidence</strong><span>This visual was generated by {run.briefing_video_model || 'Veo'} from the validated run summary. Findings, measurements, and provenance remain in the evidence package.</span></div></div>
      <section className="briefing-finding"><span>Validated finding used as context</span><p>{run.final_summary}</p></section>
      <footer><span>SHA-256 {artifact.sha256.slice(0, 16)}…</span><a className="download-button" href={source} download><Download size={15} /> Download MP4</a></footer>
    </section>
  </div>
}
